### ISSUE TITLE
Next step in flow

### ISSUE THREAD

**Issue by wohlbier** [GiorgioZacharo/AccelSeeker#3]
Hi, what is the next step in the tool flow. If I have acceleration candidates how do I turn them into accelerators?
Thanks.

**Comment by GiorgioZacharo** [comment]
Hi John and thank you for your interest in our tool-chain. Our flow currently receives the source code of applications as input and automatically detects suitable candidates for acceleration provided a HW area budget. The output of AccelSeeker is a selection of HW accelerators to be implemented, which then needs to be synthesized. Our tool-chain, at the moment, does not perform HLS. So the output of AccelSeeker is the HW/SW design, i.e., the decision of which part of the computation should stay in SW and which part should be implemented in HW.
